# GoReleaser configuration for heyman
project_name: heyman

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    main: ./cmd/heyman

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Homebrew tap
brews:
  - name: heyman
    homepage: https://github.com/alecf/heyman
    description: "LLM-powered man page Q&A"
    license: "MIT"
    repository:
      owner: alecf
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "heyman"
    test: |
      system "#{bin}/heyman --version"
